/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example;

import io.servicetalk.http.netty.HttpServers;
import io.servicetalk.http.router.jersey.HttpJerseyRouterBuilder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.ws.rs.core.Application;
import java.util.Set;

public class App extends Application {

    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) throws Exception {
        logger.info("starting server on https://localhost:8080");
        HttpServers.forPort(8080)
                .listenStreamingAndAwait(
                        new HttpJerseyRouterBuilder()
                                .buildStreaming(new App()))
                .awaitShutdown();
    }

    @Override
    public Set<Class<?>> getClasses() {
        return Set.of(TimeResource.class);
    }
}
